### ISSUE TITLE
Add unsolicited notification

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#171] opened 2016-11-16 16:33 UTC
There is currently some issue with observation in LWM2M.

1) We face several issues with observation on DTLS in NAT environment. #161 #137 #115
  ==> this sounds not completely addressed.
2) We also raise a problem when observing large object  #76
   ==>this will not be addressed.

It also seems to me that CoAP observation was mainly for live synchronization of a client resource with the server. (like telemetry)

We (at sierra wireless) face use cases where there is no need to start or stop observation, but the device just need to push resource to the server with long silent period.

Should we imagine a kind of "Unsolicited notification" ?

I think @boaks proposed this kind of idea by sending CoAP POST on rd/registerid with the resource payload and the corresponding resource path.

This kind of solution is not impacted by issues raised above.

WDYT ?

**Comment by SHardinATT** [comment] 2016-12-21 11:25
Yes, a very much needed capability for wireless. Is there really no way to do this with the present standard implementation? That would be a gross oversight if not possible.

**Comment by ovidiu-usturoi** [comment] 2017-06-28 17:39
The idea with the observed mechanism is to have a good synchronization between the devices. Usually, in a wireless network, we don't want to flood the air with unsolicited messages.  There could be some messages that are of interest for a specific server, but in this case using the right values for min/max period we can simulate an unsolicited notification.

**Comment by sbernard31** [comment] 2017-06-29 08:51
I mean that observation is technically complex. I pointed technical issues above.
The idea of proposing "Unsolicited notification" is to avoid this complexity for use case where this complexity is in practice totally useless.

Using observation to simulate "Unsolicited notification" does not help at all.

**Comment by boaks** [comment] 2017-06-29 09:29
In my opinion, OMA-TS-LightweightM2M-V1_0-20170208-A, section 8.2.6, map the "reporting interface" to RFC7641, but that RFC causes more technical trouble (see https://www.ietf.org/mail-archive/web/core/current/msg07813.html) then it was intended.

This is mainly the request/response mapping as defined in RFC7252, especially if DTLS and long term observes are in play. There were several e-mail discussions in the ietf-core-list, so let me point to one of the last contributions https://www.ietf.org/mail-archive/web/core/current/msg08821.html
 
In my opinion the main question is, what should be used as long term identity?
With RFC7641 that "long term identity" would be located either in DTLS or in CoAP.
So it seems, that LWM2M has to wait for a conclusion there.

> I think @boaks proposed this kind of idea by sending CoAP POST on rd/registerid with the resource payload and the corresponding resource path. 

Therefore my idea was to offer an additional mapping for the "reporting interface" using a device request for a "Notify" (in the meaning of LWM2M 5.5.2), where that "notify request" could provide the long term identity used by LWM2M, the registration location.
The other definitions of LWM2M 5.5 can still be in place, but must be also mapped alternatively. The main difference according traffic would be, that RFC7641 may use one NON message (if this matches really your requirement), but the device request message would always be answered by a response (or ack) message (as a CON notify would also be).

**Comment by boaks** [comment] 2017-06-29 11:30
And just to say, I'm not that sure, that the LWM2M TS does really comply to RFC7641.
I think, there are more "expectations" on that RFC, then "understanding" what it is really for.

OMA-TS-LightweightM2M-V1_0-20170208-A, 6.4.4 JSON 

> Historical version of notifications are typically generated when “Notification Storing When Disabled or Offline” resource of LwM2M Server Object is set to true (see Appendix D.2) and when the Device comes on line after having been disabled for a period of time.

This is just also not in the spirit of RFC7641:
RFC7641 will just response multiple times to a GET, so that, if the resource is changed, this change is transferred with out a GET but contains exactly the same data as such a new GET would receive as response. So the idea of having such an "historical list" would violate that. 

See RFC7641, 1.2

> Notification: Whenever the state of a resource changes, the server
> notifies each client in the list of observers of the resource.
> Each notification is an additional CoAP response sent by the
> server in reply to the single extended GET request and includes a
> complete, updated representation of the new resource state.   

"new resource state" not "list of changes"

**Comment by hannestschofenig** [comment] 2017-11-01 17:35
@sbernard31, you are asking for a new feature in LwM2M. As an OMA member please contribute text for your "unsolicited notification" to the work on LwM2M v1.1.

**Closed by hannestschofenig** 2017-11-01 17:35 UTC

**Comment by ssps12** [comment] 2018-04-26 05:51
I am trying to implement observe and notify in my lwm2m wakaama based client in c and leshan server.The server is not getting auto observe and on client side for example temperature object data is changing but client is not pushing the value towards the server. what should be added on client side so that this will work properly.

**Comment by boaks** [comment] 2018-04-28 14:14
What do you mean by "auto observe"?
Are you sure, your idea complies to the LWM2M TS? This issue was about to change/extend LWM2M to overcome technical issues of long term observations using RFC7641. Though your wording in your comment seems to use RFC7641, there is simply nothing as a "auto observe"! You must explizitly establish a observe relation by sending a observe request to the LWM2M client (coap-server) and then the LWM2M client will notify you by sending a notification. But if your client address changes, or your DTLS session gets "renewed", then your notify will be ignored. There are work-arounds, e.g. reestablish the observe relation frequently, but this would require, that you know, how frequently your application would require such reestablished observe.

**Comment by sbernard31** [comment] 2021-02-23 09:15
Just in case someone found this issue now : 
This feature is now part of LWM2M since v1.1, called `Send Operation` : see [core§6.4.6](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-4-6-0-646-Send-Operation)
