### ISSUE TITLE
Allow to include uri-path and uri-queries in LwM2M Server URI (`/0/0/0`)

### ISSUE THREAD

**Issue by szysas** [OpenMobileAlliance/OMA_LwM2M_for_Developers#240] opened 2017-11-02 11:56 UTC
* `OMA-TS-LightweightM2M-V1_0_1-20170704-A`
* section: E.1

Allow to include uri-path and any uri-query in a resource of LwM2M server URI (`/0/0/0`). 
This will enable passing extra information (like tenancy) to LwM2M server.

_For example:_
`coaps://example.com:5684/my-creazy-rd?parameter=value`
then client registers:
`POST coaps://example.com:5684/my-creazy-rd?parameter=value&ep=device0123`

**Comment by kFYatek** [comment] 2017-11-03 10:39
I believe this may be a duplicate of issue #230.

**Comment by hannestschofenig** [comment] 2017-11-20 13:47
This is a duplicate

**Closed by hannestschofenig** 2017-11-20 13:47 UTC
