### ISSUE TITLE
OMNA-Registration of Event Log

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#416] opened 2018-10-13 07:46 UTC
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-10-13 07:46:07 UTC</td></tr><tr><td>Submitter's name</td><td>zaqiot</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>zaqiot</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Event Log</td></tr><tr><td>Object Description</td><td>SD51NB is a NB-IoT based smoke detector</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=7fe8d579-f58b-4498-938f-7d5287e2a0cc_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/7fe8d579-f58b-4498-938f-7d5287e2a0cc_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=7fe8d579-f58b-4498-938f-7d5287e2a0cc_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment] 2018-10-14 00:56
Duplicate of OMNA-Registration of Event Log [#415](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/415)

**Closed by seanmcilroy29** 2018-10-14 00:56 UTC
Labels: OMNA-Registration
