### ISSUE TITLE
Invalid "Sensor Units" resources in IPSO objects

### ISSUE THREAD

**Issue by jvsalo** [OpenMobileAlliance/OMA_LwM2M_for_Developers#269] opened 2017-12-14 12:46 UTC
Some (if not most) of the IPSO objects have "Sensor Units" resources with type set to "Float", while it should obviously be "String", e.g., http://www.openmobilealliance.org/tech/profiles/lwm2m/3323.xml

This has already been fixed upstream (https://github.com/IPSO-Alliance/pub/tree/master/reg), but http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html has not been updated.

**Comment by seanmcilroy29** [comment] 2017-12-27 09:09
Resources in Object 3323 have been updated by [IPSO](https://github.com/IPSO-Alliance/pub/commit/72b4bf06977b124d7fd8f8814ad95357cacc7fe7#diff-3a60ec06ff2db5b4fb2658a1149bbae0) from 'String' to 'Float' by IPSO

This update will now be added as an issue for the DM WG to review

**Comment by boaks** [comment] 2018-01-12 09:05
Duplicate of #212 

So long time pending ...

**Comment by jaimejim** [comment] 2018-01-16 20:23
As I said in #212 the issue is fixed from my pov since May 2017. 
OMA should update to the latest version upstream as @jvsalo pointed out.

**Closed** 2022-10-04 20:12 UTC
Labels: IPSO
